### ISSUE TITLE
Req: Save loadout to launch, otherwise you get "System.Exception: 2 guardians must be used"

### ISSUE THREAD

**Issue by LockMan007** [MopsieX/OMDU-SinglePlayer#26]
Requires you to go to Loadout Editor and save it, before launch, but doesn't tell you that.
If you just click "Launch" it stops you with that error.
Easiest patch would be in that blank area beside the Mods button and under Reset Configs just add the text label "Save in Loadout editor before clicking Launch, otherwise you get an error about not having 2 guardians."
************** Exception Text **************
System.Exception: 2 guardians must be used
   at SingleplayerLauncher.Hero.ApplyGuardians()
   at SingleplayerLauncher.Hero.ApplyLoadoutChanges()
   at SingleplayerLauncher.LauncherMainForm.btnLaunch_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by TimeMaster18** [comment]
A known issue for that version.

A bit late but, you might want to check this fork with a little extra feature and some bugfix: https://github.com/TimeMaster18/OMDU-SinglePlayer
